[[shards]]
idx = 0
name = "Chisinau"
address = "localhost:8080"

[[shards]]
idx = 1
name = "Balti"
address = "localhost:8081"

[[shards]]
idx = 2
name = "Orhei"
address = "localhost:8082"

[[shards]]
idx = 3
name = "Cahul"
address = "localhost:8083"
