replication_factor = 2
consistency_level = 1
transport_protocol = "http"
storage_module = "lsm"
logs = true

[[shards]]
idx = 0
name = "Chisinau"
address = "node1:8080"

[[shards]]
idx = 1
name = "Balti"
address = "node2:8081"

[[shards]]
idx = 2
name = "Orhei"
address = "node3:8082"
