replication_factor = 2
consistency_level = 1
transport_protocol = "http"
storage_module = "lsm"
logs = false

[[shards]]
idx = 0
name = "Chisinau"
address = "127.0.0.0:8080"

[[shards]]
idx = 1
name = "Balti"
address = "127.0.0.0:8081"

[[shards]]
idx = 2
name = "Orhei"
address = "127.0.0.0:8082"
