replication_factor = 3
consistency_level = 2

[[shards]]
idx = 0
name = "Chisinau"
address = "127.0.0.0:8080"

[[shards]]
idx = 1
name = "Balti"
address = "127.0.0.1:8081"

[[shards]]
idx = 2
name = "Orhei"
address = "127.0.0.2:8082"

[[shards]]
idx = 3
name = "Cahul"
address = "127.0.0.3:8083"
