@startuml

actor Client as C
box "Distributed Data Store"
participant "Coordinator Node" as CN
end box


C -> CN : Get key X
activate CN
CN -> CN : Read key X
CN -->> C : Key & Value
deactivate CN

@enduml