@startuml

title Replication Factor=2, Consistency Level=1

actor Client as C
box "Distributed Data Store"
participant "Coordinator Node" as CN
participant "Replica 1" as N1
participant "Replica 2" as N2
participant "Replica 3" as N3
end box


C -> CN : Get key X
CN -> N1 : Read key X
N1 -> CN : Error, status = 500

CN -> N2 : Read key X
N2 -> CN : Key & Value
CN -> C : Key & Value


@enduml