@startuml

title Replication Factor=3, Consistency Level=2

actor Client as C
box "Distributed Data Store"
participant "Coordinator Node" as CN
participant "Replica 1" as N1
participant "Replica 2" as N2
participant "Replica 3" as N3
end box


C -> CN : Set key X value Y
activate CN
CN -> CN : Write key X value Y
CN -->> CN : ACKs
CN -> N2 : Write key value
activate N2
CN -> N3 : Write key value
activate N3
N2 -->> CN : ACKs
deactivate N2
CN -->> C : Key & Value
deactivate CN
N3 -->>X CN
deactivate N3
@enduml