@startuml

actor Client as C
box "Distributed Data Store"
participant "Coordinator Node" as CN
participant "Replica 1" as N1
participant "Replica 2" as N2
end box


C -> CN : Get key X
activate CN
CN -> N1 : Read key X
activate N1
N1 -->> CN : Key & Value
deactivate N1
CN -->> C : Key & Value
deactivate CN

C -> CN : Get key Y
activate CN
CN -> N2 : Read key Y
activate N2
N2 -->> CN : Key & Value
deactivate N2
CN -->> C : Key & Value
deactivate CN
@enduml