@startuml

title Replication Factor=3, Consistency Level=2

actor Client as C
box "Distributed Data Store"
participant "Coordinator Node" as CN
participant "Replica 1" as N1
participant "Replica 2" as N2
participant "Replica 3" as N3
end box


C -> CN : Get key X
activate CN
CN -> N1 : Read key X
activate N1
N1 -->>x CN : Key & Value
deactivate N1

note right
Message did not reach because
of 1 second timeout
end note

CN -> N2 : Read key X
activate N2
N2 -->> CN : Key & Value
deactivate N2
CN -->> C : Key & Value
deactivate CN

@enduml